x-common-dns: &localstack-dns
  dns:
    - 10.0.2.20

services:
  localstack:
    image: localstack/localstack:4.7
    environment:
      - SERVICES=sns,sqs,s3
      - DEBUG=1
    ports:
      - "4566:4566"
    healthcheck:
      test: [ "CMD", "python", "/localstack-healthcheck.py" ]
      interval: 1s
      timeout: 2s
      retries: 40
    networks:
      default:
        ipv4_address: 10.0.2.20
    volumes:
      - ./localstack-healthcheck.py:/localstack-healthcheck.py:ro

  my-app:
    container_name: first-microservice
    <<: *localstack-dns
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      localstack:
        condition: service_healthy
    env_file:
      - ./aws-localstack-env/aws.localstack.env
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
    command: "npm run dev"

networks:
  default:
    name: localstacknet
    ipam:
      config:
        - subnet: 10.0.2.0/24
